# Generated by Django 2.2.7 on 2024-02-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('shopid', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='documents/')),
                ('shopname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('contectno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('block_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=20)),
                ('aboutproduct', models.CharField(max_length=100)),
                ('aboutservice', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=20)),
                ('shop_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=40)),
                ('cust_id', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('grandtotal', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=50)),
                ('cust_id', models.CharField(max_length=50)),
                ('order_no', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('pay_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShopReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.CharField(max_length=20)),
                ('shopname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contectper', models.CharField(max_length=40)),
                ('contectno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('block_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
    ]
